### ISSUE TITLE
HTTP Port from .env is not used, 

### ISSUE THREAD

**Issue by ThetaGamma** [jschirrmacher/tasmota-prometheus-gateway#122]
Hi @jschirrmacher !
I build the app in a container and got it up and running. The connection to my MQTT Server seems to work but I noticed, the HTTP_PORT Variable is not used from the app and it even doesn't spin up on the default port 3000, but on 8080

 ### steps to reproduce

- create a container

`docker build -t mqtt-prometheus-gateway .  `

- my .env.m-p-g
```
# The MQTT broker name or IP address of it where to subscribe to for energy meter information. Don't use the protocol here
MQTT_BROKER=mosquitto

# The MQTT port number, it defaults to 1338, if this variable is not set.
MQTT_PORT=1883

# User name and password to use to authenticate at the MQTT broker. If not specified, use anonymous access.
MQTT_USER=
MQTT_PASSWORD=

# The HTTP server port to publish the prometheus /metrics route on, defaults to 3000
HTTP_PORT=13000
```

- start with my own docker_compose.yaml
```yaml
version: "3"
services:
  mqtt-prometheus-gateway:
    image: mqtt-prometheus-gateway
    container_name: mqtt-prometheus-gateway
    hostname: mqtt-prometheus-gateway
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./.env.m-p-g:/app/.env
      - ./config.yaml:/config.yaml
    networks:
      - web
    security_opt:
      - no-new-privileges:true
    ports:
      - 13000:8080
    restart: unless-stopped

networks:
  web:
    external: true
```
- inside the container a `netstat -an` shows it's listening to 8080 and exposing the port as shown in the docker-compose port mapping let's me connect to 13000 with `curl` (but with an error - see next issue :-) )
```
/app $ netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.11:40863        0.0.0.0:*               LISTEN      
tcp        0      0 192.168.160.22:43592    192.168.160.12:1883     ESTABLISHED 
tcp        0      0 :::8080                 :::*                    LISTEN      
udp        0      0 127.0.0.11:54231        0.0.0.0:*                           
```
