### ISSUE TITLE
Enhancement: work with raw values

### ISSUE THREAD

**Issue by ThetaGamma** [jschirrmacher/tasmota-prometheus-gateway#125]
Hi @jschirrmacher 

I have several sources in my MQTT, that don't deliver JSON, but single (raw) values (e.g. vzlogger). These are not processed in the current version. I enhanced the MQTTClient.ts so it's detected whether the input is JSON or a raw value. Frankly, I'm not a typescript programmer, but I got some AI help, so it might look clumsy. But hey: it works! 

To define a raw source, I use the following in `config.yaml`:

```yaml
 - name: electric_meter_bezug
    description: The kWh from the EVU
    type: counter
    topic: vzlogger/data/chn0/raw
    path: value
  - name: electric_meter_einspeisung
    description: The kWh to the EVU
    type: counter
    topic: vzlogger/data/chn1/raw
    path: value
  - name: electric_meter_actual
    description: The kWh actual measured
    type: gauge
    topic: vzlogger/data/chn2/raw
    path: value
```

I went through GIT hell and was not able to create a PR based on your last PR, so please find the proposed code here

```typescript
import * as actualMqtt from "mqtt"
import { type MqttClient } from "mqtt"
import { flatten } from "useful-typescript-functions"
import { metrics } from "./MetricsModel"
import { type BaseType, Configuration } from "./types"

function unique<T>(list: T[]) {
  return [...new Set(list)]
}

export interface MQTT {
  connect(url: string): MqttClient
}

interface Logger {
  info: (msg: string | object) => void
  error: (msg: string | object) => void
  debug: (msg: string | object) => void
}

const regExStr = "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z"
const dateTimeRegEx = new RegExp(regExStr)
const invalidDateTimeRegEx = new RegExp('(?<!")(' + regExStr + ')(?!")', "g")

export default function (
  config: Configuration,
  mqtt: MQTT = actualMqtt,
  logger: Logger = console
) {
  const user = config.MQTT_USER
  const pwd = config.MQTT_PASSWORD
  const brokerName = config.MQTT_BROKER ?? "localhost"
  const port = config.MQTT_PORT ?? "1883"
  const auth = user && pwd ? `${user}:${pwd}@` : ""

  const client = mqtt.connect(`mqtt://${auth}${brokerName}:${port}`)
  const topics = unique(config.metrics.map((metric) => metric.topic))

  client.on("connect", () => {
    logger.info(`Connection to mqtt://${brokerName}:${port} established`)

    topics.forEach((topic) => {
      client.subscribe(topic, (err) => {
        if (err) {
          logger.error(
            `Subscription of topic '${topic}' failed: ${JSON.stringify(err)}`
          )
        } else {
          logger.info(`Topic '${topic}' subscribed, waiting for data...`)
        }
      })
    })
  })

  client.on("message", (topic, message) => {
    const rawData = message.toString().replaceAll(invalidDateTimeRegEx, '"$1"')

    let jsonData: Record<string, unknown> | null = null

    try {
      // Check if the message is JSON
      if (rawData.startsWith("{") && rawData.endsWith("}")) {
        jsonData = JSON.parse(rawData, (_, value) => {
          if (typeof value === "string" && value.match(dateTimeRegEx)) {
            return new Date(value)
          }
          return value
        })
      } else {
        // If it's a single value, wrap it in a JSON object with a default key
        jsonData = { value: rawData }
      }

      // Flatten the JSON object
      const values = flatten(jsonData)
      logger.debug({ topic, values })

      // Store the parsed values in the metrics
      metrics[topic] = values as Record<string, BaseType>
    } catch (error) {
      logger.error({
        error: (error as Error).message,
        rawData,
        topic,
      })
    }
  })

  client.on("error", (error) => logger.error({ error }))

  client.on("disconnect", () =>
    logger.info(`mqtt://${brokerName}:${port} disconnected`)
  )
}

```
